## Array continue 


In [2]:
import numpy as np

a= np.array([12,23,45,76,54,89,0,100,-8,60,56])
a[0]

12

In [4]:
a[2]

45

In [6]:
a[2:5]

array([45, 76, 54])

In [8]:
a[:5]

array([12, 23, 45, 76, 54])

In [4]:
a[5:]

array([ 89,   0, 100,  -8,  60,  56])

In [20]:
arr2D = np.array([[21,45,67,44],[78,66,56,78],[44,67,43,78],[44,67,43,78]])
arr2D

array([[21, 45, 67, 44],
       [78, 66, 56, 78],
       [44, 67, 43, 78],
       [44, 67, 43, 78]])

In [22]:
arr2D[1,2]
print(arr2D.shape)

(4, 4)


In [24]:
arr2D[1:3,1:3]

array([[66, 56],
       [67, 43]])

In [26]:
print(sum(arr2D))    # return the sum of the every raw

[187 245 209 278]


In [30]:
print(arr2D*2)   # multiply every element by 2 

[[ 42  90 134  88]
 [156 132 112 156]
 [ 88 134  86 156]
 [ 88 134  86 156]]
