## File imports in here 

In [201]:
import pandas as pd    # we have to manipulate the data 
import numpy as np # for numerical operations 
from sklearn.model_selection import train_test_split   # this will split the data set into two parts train and test 
from sklearn.linear_model import LinearRegression  # create a linear regression model
from sklearn.metrics import mean_squared_error  # this function evaluate the actual predicted value and the true test value 
import matplotlib.pyplot as plt

## Import the data set 

In [86]:
data = pd.read_csv("C:\\Users\\sdara\\Desktop\\HousingData.csv")

In [88]:
data.head()   # we can check the data set  first 5 rows 

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

## step 03 :  Choose the  x and Y and convert these tabulars formates to 2D arrays 

In [90]:
x = data.iloc[:,:12].values    # input 
y = data.iloc[:,12].values   # out put
# value convert data into arrays 



## step 04 :  Split the data set into train and test data 

- train_test_split(x,y,test_size=0.2)   -> this method have three parameters x , y and the size of test test data set 0.2 means 20%
- The above method will return the 4 arrays . They are x train , x test , y train , y test
- The function will divide the data set in random way so we have to stop that we will use the random_state = 0 for that

In [175]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=3)
x_train

array([[9.51363e+00, 0.00000e+00, 1.81000e+01, ..., 6.66000e+02,
        2.02000e+01, 6.68000e+00],
       [4.03841e+00, 0.00000e+00, 1.81000e+01, ..., 6.66000e+02,
        2.02000e+01, 3.95330e+02],
       [3.70500e-02, 2.00000e+01, 3.33000e+00, ..., 2.16000e+02,
        1.49000e+01, 3.92230e+02],
       ...,
       [1.90730e-01, 2.20000e+01, 5.86000e+00, ..., 3.30000e+02,
        1.91000e+01, 3.93740e+02],
       [1.12658e+00, 0.00000e+00, 1.95800e+01, ..., 4.03000e+02,
        1.47000e+01, 3.43280e+02],
       [3.67822e+00, 0.00000e+00, 1.81000e+01, ..., 6.66000e+02,
        2.02000e+01, 3.80790e+02]])

## Train the model by giving the x and y to the model 

In [178]:
model = LinearRegression() 


In [180]:
model.fit(x_train,y_train)

LinearRegression()

## The equation for multiple linear regression is: 

Where:

- y is the dependent variable (output/predicted value).
- x_1, x_2, ..., x_n are the independent variables (inputs).
- β_0 is the intercept (constant term).
- β_1, β_2, ..., β_n are the coefficients (weights) for each independent variable.
- ε is the error term (the residual difference between the predicted and actual values).

In [183]:
model.intercept_    

28.63730107800616

In [185]:
model.coef_ 

array([ 9.05535952e-02,  1.60308348e-02,  8.96391066e-02, -1.71319356e+00,
        7.99171540e+00, -4.38204917e+00,  8.61549018e-02,  2.02913589e-01,
       -1.16242881e-02,  7.77080880e-04,  1.37451964e-01, -9.96350156e-03])

##  Measures how well the model's predictions fit the actual data. 

Purpose:
- R^2 score indicates how well the independent variables explain the variability in the dependent variable.
- A value of 1 means perfect prediction (the model explains all the variability in the data).
- A value of 0 means the model explains no variability (equivalent to just predicting the mean).
- Negative values indicate that the model performs worse than a horizontal line (predicting the mean of the target).

In [188]:
model.score(x_train,y_train)*100    # convert it to the Perecentage 

66.01194486403686

## Get the predicted values by using the x_test data set 

## Calculate the Mean Square Error

- MSE measures how far the predicted values are from the actual values. It averages the square of the differences between predicted and actual values, giving a sense of how much error exists between the predictions and the real data.
- Lower MSE indicates better model performance.

## Get the Root Mean Squared Error - RMSE 
- RMSE gives an error metric in the same units as the target variable (since it's the square root of the MSE).
- It provides an intuitive understanding of how much error the model is making, in terms of the actual output variable's scale.


In [191]:
y_pred = model.predict(x_test)

In [193]:
MSE = mean_squared_error(y_pred,y_test)
MSE

16.062769226878967

In [195]:
RMSE = np.sqrt(MSE)
RMSE

4.007838473152201

In [197]:
arr = np.array([0.07,17.6,2.67,0.678,6.45,67.54,4.04,1,295,15.3,397.6,4.85]).reshape(1,12)

In [199]:
model.predict(arr)

array([-164.67718146])