## numpy library 

- this library is using for calculating and doing some mathematical things 

In [4]:
import numpy as np

np.sqrt(4)


2.0

In [10]:
np.power(4,5)

1024

In [14]:
np.round(3.76)    ## round off nearest integer

4.0

In [20]:
np.sin(180)    # angles are in rad value

-0.8011526357338304

In [22]:
np.cos(1)

0.5403023058681398

In [24]:
np.tan(3)

-0.1425465430742778

In [26]:
np.log(100)

4.605170185988092

## Array using the numpy lib


In [6]:
L = [10,20,30,40]
np.array(L)

array([10, 20, 30, 40])

In [8]:
R=np.array([50,50,60,70])     # one dimenational array 
print(R)

[50 50 60 70]


In [10]:
DDA =  np.array([[10,20],[30,40],[70,80]])    ## two dimnetional Array 
print(DDA)

[[10 20]
 [30 40]
 [70 80]]


In [12]:
print(DDA.shape)

(3, 2)
